CREATE TABLE IF NOT EXISTS suppliers (
    id VARCHAR(255) PRIMARY KEY,
    partner_id VARCHAR(255) NOT NULL,
    partner_name VARCHAR(255) NOT NULL,
    customer_id VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_domain_name VARCHAR(255) NOT NULL,
    customer_country VARCHAR(255) NOT NULL,
    mpn_id INTEGER NOT NULL,
    tier2_mpn_id INTEGER NOT NULL,
    invoice_number VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    sku_id VARCHAR(255) NOT NULL,
    availability_id VARCHAR(255) NOT NULL,
    sku_name VARCHAR(255) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    publisher_name VARCHAR(255) NOT NULL,
    publisher_id VARCHAR(255),
    subscription_description TEXT,
    subscription_id VARCHAR(255) NOT NULL,
    charge_start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    charge_end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    usage_date TIMESTAMP WITH TIME ZONE NOT NULL,
    meter_type VARCHAR(255) NOT NULL,
    meter_category VARCHAR(255) NOT NULL,
    meter_id VARCHAR(255) NOT NULL,
    meter_sub_category VARCHAR(255) NOT NULL,
    meter_name VARCHAR(255) NOT NULL,
    meter_region VARCHAR(255),
    unit VARCHAR(255) NOT NULL,
    resource_location VARCHAR(255) NOT NULL,
    consumed_service VARCHAR(255) NOT NULL,
    resource_group VARCHAR(255) NOT NULL,
    resource_uri TEXT NOT NULL,
    charge_type VARCHAR(255) NOT NULL,
    unit_price DECIMAL(20,12) NOT NULL,
    quantity DECIMAL(20,12) NOT NULL,
    unit_type VARCHAR(255) NOT NULL,
    billing_pre_tax_total DECIMAL(20,12) NOT NULL,
    billing_currency VARCHAR(3) NOT NULL,
    pricing_pre_tax_total DECIMAL(20,12) NOT NULL,
    pricing_currency VARCHAR(3) NOT NULL,
    service_info1 TEXT,
    service_info2 TEXT,
    tags JSONB,
    additional_info JSONB,
    effective_unit_price DECIMAL(20,12) NOT NULL,
    pc_to_bc_exchange_rate INTEGER NOT NULL,
    pc_to_bc_exchange_rate_date TIMESTAMP WITH TIME ZONE NOT NULL,
    entitlement_id VARCHAR(255) NOT NULL,
    entitlement_description TEXT NOT NULL,
    partner_earned_credit_percentage INTEGER NOT NULL,
    credit_percentage INTEGER NOT NULL,
    credit_type VARCHAR(255) NOT NULL,
    benefit_order_id VARCHAR(255),
    benefit_id VARCHAR(255),
    benefit_type VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_suppliers_partner_id ON suppliers(partner_id);
CREATE INDEX idx_suppliers_customer_id ON suppliers(customer_id);
CREATE INDEX idx_suppliers_subscription_id ON suppliers(subscription_id);
CREATE INDEX idx_suppliers_usage_date ON suppliers(usage_date);
CREATE INDEX idx_suppliers_deleted_at ON suppliers(deleted_at);
CREATE INDEX idx_suppliers_customer_name_trgm ON suppliers USING gin (customer_name gin_trgm_ops);